version: 2
updates:
- package-ecosystem: pip
  directory: "/docs"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  commit-message:
    prefix: build(deps-doc)
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "11:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  assignees:
    - "chen-robert"
