version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: type-fest
    versions:
    - 0.21.0
    - 0.21.1
    - 0.21.2
    - 0.21.3
    - 1.0.1
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
- package-ecosystem: pip
  directory: "/docs"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mkdocs-material
    versions:
    - 6.2.8
    - 7.0.3
    - 7.0.5
    - 7.0.6
    - 7.0.7
    - 7.1.0
    - 7.1.1
    - 7.1.2
  commit-message:
    prefix: build(deps-doc)
